set CWD=%CD%

set BUILD_CONFIGURATION=Debug
set BUILD_FOLDER="build/%BUILD_CONFIGURATION%"

cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=%BUILD_CONFIGURATION% -S %CWD% -B %BUILD_FOLDER%
cmake --build %BUILD_FOLDER%