name: Node.js Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [created]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
      env:
        CC: gcc-10
        CXX: g++-10
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Get GCC 10'
      run: |
        sudo apt update
        sudo apt install gcc-10 g++-10
    - name: 'Build: Debug'
      run: bash ./build.sh Debug
    - name: 'Build: Release'
      run: build/Debug/chalet-debug build Release
    - name: 'Run: Tests'
      run: build/Release/chalet run Release tests_chalet
    - name: 'Bundle'
      run: build/Release/chalet bundle
  macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Build: Debug'
      run: bash ./build.sh Debug
    - name: 'Build: Release'
      run: build/Debug/chalet-debug build Release
    - name: 'Run: Tests'
      run: build/Release/chalet run Release tests_chalet
    - name: 'Bundle'
      run: build/Release/chalet bundle
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: 'Get MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Build: Debug'
      run: bash ./build.sh Debug
    - name: 'Build: Release'
      run: |
        echo $PATH
        echo $Path
        which g++
        which gcc
        which g++.exe
        which gcc.exe
        build/Debug/chalet-debug build Release
    - name: 'Run: Tests'
      run: build/Release/chalet run Release tests_chalet
    - name: 'Bundle'
      run: build/Release/chalet bundle
