# Note: Before creating a new major/minor release, update CURRENT_RELEASE_BRANCH

name: Chalet Release

on:
  push:
    tags:
      - "v*"
  release:
    types: [created]

jobs:
  Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Create Release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          commitish: ${{ secrets.CURRENT_RELEASE_BRANCH }}
          draft: true
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
  Linux-Ubuntu:
    needs: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      CC: gcc-11
      CXX: g++-11
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.CURRENT_RELEASE_BRANCH }}
      - name: "Get GCC 11"
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt update
          sudo apt install gcc-11 g++-11 zip debhelper uuid-dev uuid-dev:armhf ninja-build gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf binutils-arm-linux-gnueabi
      - name: "Fetch Dependencies"
        run: bash ./fetch_externals.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build: Debug"
        run: bash ./build.sh Debug
      - name: "Configure Chalet"
        run: build/Debug/chalet-debug configure
      - name: "Color Test"
        run: build/Debug/chalet-debug termtest
      - name: "Build: Release (arm)"
        run: build/Debug/chalet-debug -c Release -t arm-linux-gnueabihf-gcc -b native-experimental bundle
      - name: "Upload assets (arm)"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/chalet-arm-linux-gnueabihf.zip
            ./dist/chalet-arm-linux-debian.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
      - name: "Build: Release (x86_64)"
        run: build/Debug/chalet-debug -c Release -t x86_64-linux-gnu-gcc -b native-experimental bundle
      - name: "Upload assets (x86_64)"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/chalet-x86_64-linux-gnu.zip
            ./dist/chalet-amd64-linux-debian.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
      - name: "Run: Tests"
        run: build/x86_64-linux-gnu_Release/chalet run tests
  MacOS:
    needs: Release
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    env:
      MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
    steps:
      - name: "Prepare Environment for Signing"
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.CURRENT_RELEASE_BRANCH }}
      - name: "Fetch Dependencies"
        run: bash ./fetch_externals.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build: Debug"
        run: bash ./build.sh Debug
      - name: "Configure Chalet"
        run: |
          build/Debug/chalet-debug configure
          build/Debug/chalet-debug set options.signingIdentity $MACOS_SIGNING_IDENTITY
      - name: "Color Test"
        run: build/Debug/chalet-debug termtest
      - name: "Build: Release (x86_64)"
        run: build/Debug/chalet-debug -c Release -a x86_64 -b native-experimental bundle
      - name: "Upload assets (x86_64)"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/chalet-x86_64-apple-darwin.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
      - name: "Build: Release (arm64)"
        run: build/Debug/chalet-debug -c Release -a arm64 -b native-experimental bundle
      - name: "Upload assets (arm64)"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/chalet-arm64-apple-darwin.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
      - name: "Build: Release (universal)"
        run: build/Debug/chalet-debug -c Release -a universal -b native-experimental bundle
      - name: "Upload assets (universal)"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/chalet-universal-apple-darwin.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
      - name: "Run: Tests"
        run: build/universal-apple-darwin_Release/chalet run tests
  Windows-MSVC:
    needs: Release
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Get MSVC Environment"
        uses: ilammy/msvc-dev-cmd@v1
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.CURRENT_RELEASE_BRANCH }}
      - name: "Fetch Dependencies"
        run: bash ./fetch_externals.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Show Version Info"
        run: |
          makensis -version
      - name: "Build: Debug"
        run: ./build-vs2022.bat Debug
      - name: "Configure Chalet"
        run: build/msvc_Debug/chalet-debug configure
      - name: "Color Test"
        run: build/msvc_Debug/chalet-debug termtest
      - name: "Build: Release (x64)"
        run: build/msvc_Debug/chalet-debug -c Release -t vs-stable -a x64 -b native-experimental bundle
      - name: "Upload assets (x64)"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/chalet-x86_64-pc-windows-msvc.zip
            ./dist/chalet-x86_64-pc-windows-msvc-installer.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
      # - name: "Build: Release (arm64)"
      #   run: build/msvc_Debug/chalet-debug -c Release -t vs-stable -a arm64 -b native-experimental bundle
      # - name: "Upload assets (arm64)"
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       ./dist/chalet-arm64-pc-windows-msvc.zip
      #       ./dist/chalet-arm64-pc-windows-msvc-installer.zip
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     draft: true
      #     prerelease: false
      - name: "Run: Tests"
        run: build/msvc_Debug/chalet-debug run tests
