# Note: Before creating a new major/minor release, update CURRENT_RELEASE_BRANCH

name: MacOS
on:
  pull_request:
  push:
    branches:
      - main
env:
  RELEASE_PREFIX: "Chalet"
  GENERATE_TIMESTAMP: "echo \"timestamp=$(date +'%Y%m%d%H%M')\" >> $GITHUB_OUTPUT"
  IS_BRANCH: ${{ github.ref_type == 'branch' }}
  CI: 1
defaults:
  run:
    shell: bash
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [macos-12]
        triplet: [arm64-apple-darwin, x86_64-apple-darwin, universal-apple-darwin]
        include:
          - triplet: arm64-apple-darwin
            arch: arm64
          - triplet: x86_64-apple-darwin
            arch: x86_64
          - triplet: universal-apple-darwin
            arch: universal
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.triplet }}
    env:
      CHALET_BIN: bin/universal-macos/chalet
      MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
      MACOS_APPLE_ID: ${{ secrets.MACOS_APPLE_ID }}
      MACOS_CHALET_APP_PWD: ${{ secrets.MACOS_CHALET_APP_PWD }}
      MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_IDENTITY }}
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
    steps:
      - name: "Prepare Environment for Signing"
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      - name: "Create Keychain profile"
        run: xcrun notarytool store-credentials "ChaletProfile" --apple-id "$MACOS_APPLE_ID" --password "$MACOS_CHALET_APP_PWD" --team-id "$MACOS_TEAM_ID"
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: "Get Packages"
        run: brew install ninja
      - name: "Color Test"
        run: ${{ env.CHALET_BIN }} termtest
      - name: "Fetch Dependencies"
        run: bash ./fetch_externals.sh
      - name: "Build"
        run: ${{ env.CHALET_BIN }} -c Release -t ${{ matrix.arch }} -b native bundle
      - name: "Notarize"
        run: |
          xcrun notarytool submit ./dist/chalet-${{ matrix.triplet }}.zip --keychain-profile "ChaletProfile" --wait
      - name: "Run: Tests"
        if: matrix.crossBuild != true
        run: ${{ env.CHALET_BIN }} run tests
      - name: "Upload"
        uses: ncipollo/release-action@v1
        env:
          BRANCH_RELEASE_NAME: ${{ github.ref_name }}-${{ steps.timestamp.outputs.timestamp }}
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          name: ${{ env.RELEASE_PREFIX }} ${{ env.IS_BRANCH && env.BRANCH_RELEASE_NAME || github.ref_name }}
          tag: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          allowUpdates: true
          generateReleaseNotes: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          artifacts: dist/chalet-${{ matrix.triplet }}.zip
          draft: true
          prerelease: true
