# Note: Before creating a new major/minor release, update CURRENT_RELEASE_BRANCH

name: Create Release
on:
  pull_request:
  push:
    branches:
      - main
env:
  GENERATE_TIMESTAMP: "echo \"timestamp=$(date +'%Y%m%d%H%M')\" >> $GITHUB_OUTPUT"
  RELEASE_PREFIX: "Chalet"
  IS_BRANCH: ${{ github.ref_type == 'branch' }}
  IS_PRERELEASE: true
  CI: 1
defaults:
  run:
    shell: bash
jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - name: "Create Timestamp"
        run: ${{ env.GENERATE_TIMESTAMP }}
        id: timestamp
      - name: "Upload"
        uses: ncipollo/release-action@v1
        env:
          BRANCH_RELEASE_NAME: ${{ github.ref_name }}-${{ steps.timestamp.outputs.timestamp }}
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          name: ${{ env.RELEASE_PREFIX }} ${{ env.IS_BRANCH && env.BRANCH_RELEASE_NAME || github.ref_name }}
          tag: ${{ github.ref_name }}
          commit: ${{ github.sha }}
          allowUpdates: true
          generateReleaseNotes: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          draft: true
          prerelease: ${{ env.IS_PRERELEASE == 'true' }}